# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12post_service.proto\x12\x0bpostservice\"C\n\x04Post\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"D\n\x11\x43reatePostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"P\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\r\n\x05title\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\"0\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\"\x1c\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"?\n\x10ListPostsRequest\x12\x13\n\x0bpage_number\x18\x01 \x01(\x03\x12\x16\n\x0eposts_per_page\x18\x02 \x01(\x03\"J\n\x11ListPostsResponse\x12 \n\x05posts\x18\x01 \x03(\x0b\x32\x11.postservice.Post\x12\x13\n\x0bposts_count\x18\x02 \x01(\x03\x32\xd7\x02\n\x0bPostService\x12?\n\nCreatePost\x12\x1e.postservice.CreatePostRequest\x1a\x11.postservice.Post\x12\x39\n\x07GetPost\x12\x1b.postservice.GetPostRequest\x1a\x11.postservice.Post\x12?\n\nUpdatePost\x12\x1e.postservice.UpdatePostRequest\x1a\x11.postservice.Post\x12?\n\nDeletePost\x12\x1e.postservice.DeletePostRequest\x1a\x11.postservice.Post\x12J\n\tListPosts\x12\x1d.postservice.ListPostsRequest\x1a\x1e.postservice.ListPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POST']._serialized_start=35
  _globals['_POST']._serialized_end=102
  _globals['_CREATEPOSTREQUEST']._serialized_start=104
  _globals['_CREATEPOSTREQUEST']._serialized_end=172
  _globals['_UPDATEPOSTREQUEST']._serialized_start=174
  _globals['_UPDATEPOSTREQUEST']._serialized_end=254
  _globals['_DELETEPOSTREQUEST']._serialized_start=256
  _globals['_DELETEPOSTREQUEST']._serialized_end=304
  _globals['_GETPOSTREQUEST']._serialized_start=306
  _globals['_GETPOSTREQUEST']._serialized_end=334
  _globals['_LISTPOSTSREQUEST']._serialized_start=336
  _globals['_LISTPOSTSREQUEST']._serialized_end=399
  _globals['_LISTPOSTSRESPONSE']._serialized_start=401
  _globals['_LISTPOSTSRESPONSE']._serialized_end=475
  _globals['_POSTSERVICE']._serialized_start=478
  _globals['_POSTSERVICE']._serialized_end=821
# @@protoc_insertion_point(module_scope)
