version: '3.8'

services:

  # DBs

  db:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=db
    ports:
      - "6666:5432"
    volumes:
      - db_postgres_data:/var/lib/postgresql/data/
  
  postdb:
    image: postgres:13
    environment:
      POSTGRES_USER: postdb_user
      POSTGRES_PASSWORD: postdb_password
      POSTGRES_DB: postdb
    ports:
      - "5555:5432"
    volumes:
      - postdb_postgres_data:/var/lib/postgresql/data
      - ./post_service/init-postdb.sql:/docker-entrypoint-initdb.d/init-postdb.sql # init postDB

  statdb:
    image: yandex/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - "statdb:/var/lib/clickhouse"
      - "./stat_service/init.sql:/docker-entrypoint-initdb.d/init.sql"
    depends_on:
      broker:
        condition: service_healthy
    logging:
      driver: none

  # Services

  broker:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:31341,CONTROLLER://:31342
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker:31342
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "31341:31341"
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep -q 31341 | echo"]
    logging:
      driver: none

  post_service:
    build: 
      context: .
      dockerfile: ./post_service/Dockerfile
    ports:
      - "12345:12345"
    environment:
      - DATABASE_URI=postgresql://postdb_user:postdb_password@postdb/postdb
    depends_on:
      - postdb

  stat_service:
    build:
      context: .
      dockerfile: ./stat_service/Dockerfile
    ports:
      - "54321:54321"
    environment:
      - CLICKHOUSE_URL=statdb:9000
    depends_on:
      - statdb

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=secret_key
      - SQLALCHEMY_DATABASE_URI=postgresql://db_user:db_password@db/db
      - GRPC_POST_SERVICE=post_service:12345
      - GRPC_STAT_SERVICE=stat_service:54321
      - KAFKA_BROKER_URL=broker:31341
      - CLICKHOUSE_URL=statdb:9000
      - CLICKHOUSE_USER=STATDB
      - CLICKHOUSE_PASS=STATDB
    depends_on:
      - db
      - post_service
      - stat_service

volumes:
  db_postgres_data:
  postdb_postgres_data:
  statdb: