@startuml
!include https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Любой человек, который использует трекер задач.")

System_Boundary(c1, "Трекер задач") {
    System(tracker_api, "Главный сервис", "Отвечает за клиентское API, регистрацию и аутентификацию пользователей.")
    System(tasks_service, "Сервис задач", "Управление задачами и комментариями.")
    System(stats_service, "Сервис статистики", "Подсчет лайков и просмотров.")
}

System_Ext(mail_system, "Почтовая система", "Используется для отправки уведомлений.")

Rel(user, tracker_api, "Использует")
Rel(user, tasks_service, "Использует")
Rel(user, stats_service, "Использует")
Rel(tracker_api, mail_system, "Отправляет уведомления")

@enduml