# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import stat_service_pb2 as stat__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in stat_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class StatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPostStatistics = channel.unary_unary(
                '/statservice.StatService/GetPostStatistics',
                request_serializer=stat__service__pb2.PostStatisticsRequest.SerializeToString,
                response_deserializer=stat__service__pb2.PostStatisticsResponse.FromString,
                _registered_method=True)
        self.GetTopPosts = channel.unary_unary(
                '/statservice.StatService/GetTopPosts',
                request_serializer=stat__service__pb2.TopPostsRequest.SerializeToString,
                response_deserializer=stat__service__pb2.TopPostsResponse.FromString,
                _registered_method=True)
        self.GetTopUsers = channel.unary_unary(
                '/statservice.StatService/GetTopUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=stat__service__pb2.TopUsersResponse.FromString,
                _registered_method=True)


class StatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPostStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPostStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPostStatistics,
                    request_deserializer=stat__service__pb2.PostStatisticsRequest.FromString,
                    response_serializer=stat__service__pb2.PostStatisticsResponse.SerializeToString,
            ),
            'GetTopPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopPosts,
                    request_deserializer=stat__service__pb2.TopPostsRequest.FromString,
                    response_serializer=stat__service__pb2.TopPostsResponse.SerializeToString,
            ),
            'GetTopUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=stat__service__pb2.TopUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statservice.StatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statservice.StatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPostStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statservice.StatService/GetPostStatistics',
            stat__service__pb2.PostStatisticsRequest.SerializeToString,
            stat__service__pb2.PostStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statservice.StatService/GetTopPosts',
            stat__service__pb2.TopPostsRequest.SerializeToString,
            stat__service__pb2.TopPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statservice.StatService/GetTopUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            stat__service__pb2.TopUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
